-- Fuções de tempo

-- GATDATE()
SELECT GETDATE()
SELECT CAST(GETDATE() AS DATE) -- Cast para Date

--DATEDIFF
SELECT DATEDIFF(YEAR, '1985-03-15', GETDATE())

--DATEADD()
SELECT DATEADD(MONTH, -1, DATEADD(YEAR, -1, GETDATE())) -- PARA DIA MÊS E ANOS É ESCREVER UM DATEADD DENTRO DO OUTRO

--DATEPART()
SELECT DATEPART(WEEK, '1985-03-18') -- PODE PEGAR O DIA, MÊS, ANO, DIA DA SEMANA, E QUAL SEMANA DO ANO

--BETWEEN
SELECT * FROM tb_Vendas WHERE dtVenda BETWEEN DATEADD(YEAR, -1, GETDATE()) AND GETDATE() -- PEGAR DADOS DE UM ANO ATÉ A DATA DE HJ

--FORMAT
SELECT FORMAT(CAST(GETDATE() AS DATE), 'dd/MM/yyyy') -- FROMATAR DADOS

--- CASO DE USO:

SELECT * FROM tb_Vendas WHERE dtVenda >= FORMAT(GETDATE(), 'yyy-MM-01') -- TODAS AS VENDAS NESSE ANO